swagger: '2.0'
info:
  title: ArgentBank Transactions API
  version: 2.0.0
  description: API endpoints for viewing and editing transaction information, grouped by account and linked to a specific user.

host: localhost:3001
basePath: /
schemes:
  - http

paths:
  /users/{userId}/accounts:
    get:
      summary: List user’s bank accounts
      description: Returns the list of account IDs associated with the user.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successfully retrieved account list
          schema:
            type: array
            items:
              $ref: '#/definitions/AccountId'
        404:
          description: User not found

  /users/{userId}/accounts/{accountId}/transactions:
    get:
      summary: List transactions for an account, filtered by month
      description: View all transactions for a given account during a specific month, grouped by account.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: accountId
          in: path
          required: true
          type: string
        - name: month
          in: query
          required: false
          type: string
          example: "2025-09"
      responses:
        200:
          description: Successfully retrieved transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/TransactionShort'
        404:
          description: Account or transactions not found

  /users/{userId}/accounts/{accountId}/transactions/{transactionId}:
    get:
      summary: Get details of a transaction
      description: Returns detailed information for a specific transaction.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: accountId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Transaction details found
          schema:
            $ref: '#/definitions/TransactionFull'
        404:
          description: Transaction not found

    patch:
      summary: Edit transaction information
      description: Edit certain fields in a transaction (transactionType, note, category).
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: accountId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        200:
          description: Transaction updated successfully
        400:
          description: Invalid parameters
        404:
          description: Transaction not found

    delete:
      summary: Delete additional information from a transaction
      description: Delete the note or category from a transaction without deleting the transaction itself.
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: accountId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - name: field
          in: query
          required: true
          type: string
          enum:
            - note
            - category
      responses:
        200:
          description: Information deleted successfully
        404:
          description: Transaction or field not found

definitions:
  AccountId:
    type: object
    properties:
      accountId:
        type: string
        description: Unique identifier for the account

  TransactionShort:
    type: object
    properties:
      transactionId:
        type: string
        description: Unique transaction identifier
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      balance:
        type: number

  TransactionFull:
    type: object
    properties:
      transactionType:
        type: string
      category:
        type: string
      note:
        type: string

  TransactionUpdate:
    type: object
    properties:
      transactionType:
        type: string
      category:
        type: string
      note:
        type: string
